:arrow_up: (modules/hyprland/default.nix) Update xwaylandvideobridge package reference
error: The top-level xwaylandvideobridge alias has been removed.

Please explicitly use kdePackages.xwaylandvideobridge for the latest Qt 6-based version,
or libsForQt5.xwaylandvideobridge for the deprecated Qt 5 version.

Note that Qt 5 versions of most KDE software will be removed in NixOS 25.11.